### PR TITLE
Update branding, copy

### PR DESCRIPTION
**Pull request by hstove**
@kyranjamie and @aulneau - one thing I'm not sure how to do best is to have "Powered by Blockstack" always at the bottom of the screen. I'd love to hear your thoughts on that.

### CODE REVIEW

**Comment by kyranjamie** [comment]
Until this point, `Screen` and its children are conceptually agnostic of any content and focus purely on layout. If there's a win to be had breaking this abstraction we should, but here we can just rename it to `<PoweredBy/>`.

I reckon this component can pass as footer content. I played around with the code a little to see if my suggestion would work, will commit for you to take a look. Essentially, with some small style changes we make to `<ScreenFooter/>` to fill available space and `alignSelf` the _Powered by_ at the bottom (after making both `<Screen/>` and `<ScreenFooter/`> `flex: 1;`.

**Comment by aulneau** [comment]
> @kyranjamie and @aulneau - one thing I'm not sure how to do best is to have "Powered by Blockstack" always at the bottom of the screen. I'd love to hear your thoughts on that.

Typically for this kind of thing, we would use the base component which is a flex (of the app itself), and have the screen component stretch/grow to take the height, and have the powered by component always fixed to the bottom:

(pseudo code)
```jsx
<Flex minHeight="100vh" flexDirection="column">
  <Screen flexGrow={1}>
    ...
  </Screen>
  <PoweredBy justifySelf="flex-end" />
</Flex>
```

**Comment by hstove** [comment]
Thanks for making the changes @kyranjamie . I'm :+1: on your updates here.

**Comment by markmhx** [comment]
@hstove will make some final changes, deploy and this will skip QA

**Pull request merged**
